---
- hosts: win
  vars_files:
          - sec.yml
  tasks:
          - debug:
                  msg: "pong"
          - debug:
                  var: useri
          - win_copy:
                  content: "{{ user }} is testing"
                  dest: "C:/Users/Administrator/Desktop/simple.txt"
...
